version: "3"
services:
  web:
    image: rroggia/get-started:part3
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.2"
          memory: 1G
      restart_policy:
        condition: on-failure
    ports:
      - "4000:8080"
    networks:
      - webnet
networks:
  webnet: