apiVersion: v1
kind: ReplicationController
metadata: 
  name: spring-docker-k8-hello-world-rc
spec:
  replicas: 3
  selector:
    app: spring-docker-k8-hello-world
  template:
    metadata:   
      labels:
        app: spring-docker-k8-hello-world
    spec:
      containers:
      - name: microservice-name
        image: rroggia/spring-docker-hello-world:1.1
        ports: 
        - containerPort: 8080 