global:
   scrape_interval: 10s
   external_labels: 
      monitor: 'local-monitor'

scrape_configs:
         
   -   job_name: 'microservice-name'
       metrics_path: '/actuator/prometheus'
       static_configs:
          - targets: ['microservice-name:8080']
